#!/usr/bin/env python3
"""
Training pipeline with model comparison and scientific reporting.

Outputs per version:
- Serialized winning model artifact
- JSON metadata with comparison, metrics, error analysis, and feature importance
- Markdown report with a readable summary for the repository
"""

import argparse
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
import yaml
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.preprocessing import OrdinalEncoder, StandardScaler

from app.config import setup_logging

try:
    from xgboost import XGBClassifier
except ImportError:  # pragma: no cover - handled explicitly at runtime
    XGBClassifier = None


NUMERIC_FEATURES = [
    "Age",
    "Academic Pressure",
    "Work Pressure",
    "CGPA",
    "Study Satisfaction",
    "Job Satisfaction",
    "Work/Study Hours",
    "Financial Stress",
]

CATEGORICAL_FEATURES = [
    "Gender",
    "Sleep Duration",
    "Dietary Habits",
    "Degree",
    "Have you ever had suicidal thoughts ?",
    "Family History of Mental Illness",
]

FEATURE_NAMES = NUMERIC_FEATURES + CATEGORICAL_FEATURES
TARGET = "Depression"

DEFAULT_TRAIN_DATA = "data/training_set.parquet"
DEFAULT_VAL_DATA = "data/validation_set.parquet"
DEFAULT_CRITERIA_FILE = "config/deployment_criteria.yaml"
DEFAULT_MODEL_DIR = "models"
RANDOM_SEED = 42
TOP_FEATURES = 10
TOP_ERROR_SIGNALS = 3

SELECTION_PRIORITY = (
    "recall",
    "f1_score",
    "roc_auc",
    "precision",
    "accuracy",
)


def get_next_version(model_dir: str = DEFAULT_MODEL_DIR) -> str:
    """Return the next available model version."""
    models_dir = Path(model_dir)
    models_dir.mkdir(parents=True, exist_ok=True)

    existing = []
    for file_path in models_dir.glob("model_v*.pkl"):
        try:
            existing.append(int(file_path.stem.split("_v")[1]))
        except (ValueError, IndexError):
            continue

    return f"v{max(existing, default=0) + 1}"


def load_training_data(train_path: str, val_path: str) -> tuple[pd.DataFrame, pd.Series, pd.DataFrame, pd.Series]:
    """Load train and validation splits generated by the ETL pipeline."""
    logger = logging.getLogger(__name__)

    for path in [train_path, val_path]:
        if not Path(path).exists():
            raise FileNotFoundError(
                f"Missing required dataset: {path}. Run `python -m app.pipeline` first."
            )

    train_df = pd.read_parquet(train_path)
    val_df = pd.read_parquet(val_path)

    X_train = train_df[FEATURE_NAMES]
    y_train = train_df[TARGET].astype(int)
    X_val = val_df[FEATURE_NAMES]
    y_val = val_df[TARGET].astype(int)

    logger.info("Training samples:   %s", len(X_train))
    logger.info("Validation samples: %s", len(X_val))
    return X_train, y_train, X_val, y_val


def build_preprocessor(*, scale_numeric: bool) -> ColumnTransformer:
    """Build the preprocessing pipeline for a candidate model."""
    numeric_transformer: Any = StandardScaler() if scale_numeric else "passthrough"
    return ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, NUMERIC_FEATURES),
            (
                "cat",
                OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1),
                CATEGORICAL_FEATURES,
            ),
        ]
    )


def build_candidate_models() -> list[dict[str, Any]]:
    """Create the model registry used during comparison."""
    if XGBClassifier is None:
        raise ImportError(
            "xgboost is required for model comparison. Install requirements.txt in a Python 3.11/3.12 environment."
        )

    return [
        {
            "name": "Logistic Regression",
            "model_type": "logistic_regression",
            "preprocessor": build_preprocessor(scale_numeric=True),
            "model": LogisticRegression(max_iter=2000, random_state=RANDOM_SEED),
        },
        {
            "name": "Random Forest",
            "model_type": "random_forest",
            "preprocessor": build_preprocessor(scale_numeric=False),
            "model": RandomForestClassifier(
                n_estimators=400,
                min_samples_leaf=2,
                n_jobs=-1,
                random_state=RANDOM_SEED,
            ),
        },
        {
            "name": "XGBoost",
            "model_type": "xgboost",
            "preprocessor": build_preprocessor(scale_numeric=False),
            "model": XGBClassifier(
                n_estimators=350,
                learning_rate=0.05,
                max_depth=5,
                subsample=0.9,
                colsample_bytree=0.8,
                reg_lambda=1.0,
                objective="binary:logistic",
                eval_metric="logloss",
                random_state=RANDOM_SEED,
                n_jobs=-1,
            ),
        },
    ]


def get_positive_class_scores(model: Any, X_processed: np.ndarray) -> np.ndarray:
    """Return positive-class scores for metric computation."""
    if hasattr(model, "predict_proba"):
        return model.predict_proba(X_processed)[:, 1]

    if hasattr(model, "decision_function"):
        raw_scores = model.decision_function(X_processed)
        return 1.0 / (1.0 + np.exp(-raw_scores))

    raise AttributeError(f"Model {type(model).__name__} does not expose probabilities or scores")


def evaluate_model(model: Any, preprocessor: ColumnTransformer, X_val: pd.DataFrame, y_val: pd.Series) -> dict[str, Any]:
    """Evaluate a fitted model on validation data."""
    X_val_processed = preprocessor.transform(X_val)
    y_scores = get_positive_class_scores(model, X_val_processed)
    y_pred = (y_scores >= 0.5).astype(int)

    tn, fp, fn, tp = confusion_matrix(y_val, y_pred).ravel()
    metrics = {
        "accuracy": accuracy_score(y_val, y_pred),
        "precision": precision_score(y_val, y_pred, zero_division=0),
        "recall": recall_score(y_val, y_pred, zero_division=0),
        "f1_score": f1_score(y_val, y_pred, zero_division=0),
        "roc_auc": roc_auc_score(y_val, y_scores),
        "confusion_matrix": {
            "true_negative": int(tn),
            "false_positive": int(fp),
            "false_negative": int(fn),
            "true_positive": int(tp),
        },
    }

    return {
        "metrics": metrics,
        "y_pred": y_pred,
        "y_scores": y_scores,
    }


def check_deployment_criteria(metrics: dict[str, Any], criteria: dict[str, float]) -> tuple[bool, list[str]]:
    """Check whether a model satisfies the deployment quality gate."""
    failed_checks = []

    for name, threshold in criteria.items():
        if name.startswith("min_"):
            metric_key = name[4:]
            if metric_key in metrics and metrics[metric_key] < threshold:
                failed_checks.append(f"{metric_key} {metrics[metric_key]:.4f} < minimum {threshold}")
        elif name.startswith("max_"):
            metric_key = name[4:]
            if metric_key in metrics and metrics[metric_key] > threshold:
                failed_checks.append(f"{metric_key} {metrics[metric_key]:.4f} > maximum {threshold}")

    return len(failed_checks) == 0, failed_checks


def selection_sort_key(result: dict[str, Any]) -> tuple[Any, ...]:
    """Sort models by deployment readiness and the recall-first selection policy."""
    metrics = result["metrics"]
    return (
        result["deployment_ready"],
        metrics["recall"],
        metrics["f1_score"],
        metrics["roc_auc"],
        metrics["precision"],
        metrics["accuracy"],
    )


def select_best_candidate(results: list[dict[str, Any]]) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Choose the winning model with explicit priority on recall."""
    if not results:
        raise ValueError("No candidate results available")

    ready_results = [result for result in results if result["deployment_ready"]]
    candidate_pool = ready_results or results

    ranked = sorted(candidate_pool, key=selection_sort_key, reverse=True)
    winner = ranked[0]

    fully_ranked = sorted(results, key=selection_sort_key, reverse=True)
    for rank, result in enumerate(fully_ranked, start=1):
        result["selection_rank"] = rank
        result["selected"] = result is winner

    return winner, fully_ranked


def summarize_numeric_deltas(group_df: pd.DataFrame, reference_df: pd.DataFrame, top_n: int = TOP_ERROR_SIGNALS) -> list[dict[str, float]]:
    """Return the strongest numeric shifts between two cohorts."""
    if group_df.empty or reference_df.empty:
        return []

    rows = []
    for feature in NUMERIC_FEATURES:
        group_mean = float(group_df[feature].mean())
        reference_mean = float(reference_df[feature].mean())
        rows.append(
            {
                "feature": feature,
                "group_mean": group_mean,
                "reference_mean": reference_mean,
                "delta": group_mean - reference_mean,
            }
        )

    rows.sort(key=lambda row: abs(row["delta"]), reverse=True)
    return rows[:top_n]


def summarize_categorical_deltas(group_df: pd.DataFrame, reference_df: pd.DataFrame, top_n: int = TOP_ERROR_SIGNALS) -> list[dict[str, Any]]:
    """Return the most overrepresented categorical categories in an error cohort."""
    if group_df.empty or reference_df.empty:
        return []

    rows = []
    for feature in CATEGORICAL_FEATURES:
        group_share = group_df[feature].value_counts(normalize=True)
        reference_share = reference_df[feature].value_counts(normalize=True)

        for category in group_share.index.union(reference_share.index):
            delta = float(group_share.get(category, 0.0) - reference_share.get(category, 0.0))
            if delta <= 0:
                continue
            rows.append(
                {
                    "feature": feature,
                    "category": str(category),
                    "group_share": float(group_share.get(category, 0.0)),
                    "reference_share": float(reference_share.get(category, 0.0)),
                    "delta": delta,
                }
            )

    rows.sort(key=lambda row: row["delta"], reverse=True)
    return rows[:top_n]


def build_error_narrative(group_name: str, numeric_signals: list[dict[str, Any]], categorical_signals: list[dict[str, Any]]) -> str:
    """Create a short, human-readable error explanation."""
    fragments = []

    for signal in numeric_signals[:2]:
        direction = "higher" if signal["delta"] > 0 else "lower"
        fragments.append(f"{direction} {signal['feature']}")

    for signal in categorical_signals[:2]:
        fragments.append(f"{signal['feature']}={signal['category']}")

    if not fragments:
        return f"{group_name} did not contain enough samples for a stable profile."

    return f"{group_name} are associated mainly with " + ", ".join(fragments) + "."


def analyze_prediction_errors(
    X_val: pd.DataFrame,
    y_val: pd.Series,
    y_pred: np.ndarray,
    y_scores: np.ndarray,
) -> dict[str, Any]:
    """Build false-positive and false-negative analysis for the winning model."""
    eval_df = X_val.copy()
    eval_df[TARGET] = y_val.to_numpy()
    eval_df["predicted_label"] = y_pred
    eval_df["predicted_probability"] = y_scores

    false_positives = eval_df[(eval_df[TARGET] == 0) & (eval_df["predicted_label"] == 1)]
    true_negatives = eval_df[(eval_df[TARGET] == 0) & (eval_df["predicted_label"] == 0)]
    false_negatives = eval_df[(eval_df[TARGET] == 1) & (eval_df["predicted_label"] == 0)]
    true_positives = eval_df[(eval_df[TARGET] == 1) & (eval_df["predicted_label"] == 1)]

    fp_numeric = summarize_numeric_deltas(false_positives, true_negatives)
    fp_categorical = summarize_categorical_deltas(false_positives, true_negatives)
    fn_numeric = summarize_numeric_deltas(false_negatives, true_positives)
    fn_categorical = summarize_categorical_deltas(false_negatives, true_positives)

    total_negatives = max(int((y_val == 0).sum()), 1)
    total_positives = max(int((y_val == 1).sum()), 1)

    return {
        "false_positives": {
            "count": int(len(false_positives)),
            "rate_within_actual_negative": float(len(false_positives) / total_negatives),
            "numeric_signals": fp_numeric,
            "categorical_signals": fp_categorical,
            "summary": build_error_narrative("False positives", fp_numeric, fp_categorical),
        },
        "false_negatives": {
            "count": int(len(false_negatives)),
            "rate_within_actual_positive": float(len(false_negatives) / total_positives),
            "numeric_signals": fn_numeric,
            "categorical_signals": fn_categorical,
            "summary": build_error_narrative("False negatives", fn_numeric, fn_categorical),
        },
    }


def compute_feature_importance(
    model: Any,
    preprocessor: ColumnTransformer,
    X_val: pd.DataFrame,
    y_val: pd.Series,
    top_n: int = TOP_FEATURES,
) -> list[dict[str, float]]:
    """Compute model-agnostic permutation importance for the winning model."""
    X_val_processed = preprocessor.transform(X_val)
    result = permutation_importance(
        model,
        X_val_processed,
        y_val,
        n_repeats=10,
        random_state=RANDOM_SEED,
        scoring="roc_auc",
        n_jobs=-1,
    )

    rows = []
    for feature, importance_mean, importance_std in zip(
        FEATURE_NAMES,
        result.importances_mean,
        result.importances_std,
        strict=False,
    ):
        rows.append(
            {
                "feature": feature,
                "importance_mean": float(importance_mean),
                "importance_std": float(importance_std),
            }
        )

    rows.sort(key=lambda row: row["importance_mean"], reverse=True)
    return rows[:top_n]


def build_conclusion(winner: dict[str, Any]) -> str:
    """Create a short selection conclusion centered on recall."""
    metrics = winner["metrics"]
    recall = metrics["recall"]
    precision = metrics["precision"]
    return (
        f"{winner['name']} was selected because recall is the primary deployment priority in this project. "
        f"It reached recall={recall:.3f}, with precision={precision:.3f}, "
        f"F1={metrics['f1_score']:.3f}, and ROC-AUC={metrics['roc_auc']:.3f}."
    )


def build_markdown_report(
    version: str,
    ranked_results: list[dict[str, Any]],
    winner: dict[str, Any],
    error_analysis: dict[str, Any],
    feature_importance: list[dict[str, Any]],
) -> str:
    """Create a repository-friendly markdown report for the training run."""
    comparison_lines = [
        "| Rank | Model | Ready | Recall | Precision | F1 | ROC-AUC | Accuracy |",
        "| --- | --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]

    for result in ranked_results:
        metrics = result["metrics"]
        comparison_lines.append(
            "| "
            f"{result['selection_rank']} | "
            f"{result['name']} | "
            f"{'yes' if result['deployment_ready'] else 'no'} | "
            f"{metrics['recall']:.4f} | "
            f"{metrics['precision']:.4f} | "
            f"{metrics['f1_score']:.4f} | "
            f"{metrics['roc_auc']:.4f} | "
            f"{metrics['accuracy']:.4f} |"
        )

    cm = winner["metrics"]["confusion_matrix"]
    confusion_lines = [
        "| Actual / Predicted | 0 | 1 |",
        "| --- | ---: | ---: |",
        f"| 0 | {cm['true_negative']} | {cm['false_positive']} |",
        f"| 1 | {cm['false_negative']} | {cm['true_positive']} |",
    ]

    importance_lines = [
        "| Feature | Importance (mean ROC-AUC drop) | Std |",
        "| --- | ---: | ---: |",
    ]
    for row in feature_importance:
        importance_lines.append(
            f"| {row['feature']} | {row['importance_mean']:.5f} | {row['importance_std']:.5f} |"
        )

    fp = error_analysis["false_positives"]
    fn = error_analysis["false_negatives"]

    report_lines = [
        f"# Training Report {version}",
        "",
        "## Winning model",
        build_conclusion(winner),
        "",
        "Selection priority: deployment-ready models first, then recall, F1, ROC-AUC, precision, accuracy.",
        "",
        "## Model comparison",
        *comparison_lines,
        "",
        "## Confusion matrix",
        *confusion_lines,
        "",
        "## Error analysis",
        f"- False positives: {fp['count']} ({fp['rate_within_actual_negative']:.2%} of actual negatives). {fp['summary']}",
        f"- False negatives: {fn['count']} ({fn['rate_within_actual_positive']:.2%} of actual positives). {fn['summary']}",
        "",
        "## Global feature importance",
        *importance_lines,
        "",
    ]

    return "\n".join(report_lines)


def make_json_safe(value: Any) -> Any:
    """Convert numpy-heavy structures into JSON-serializable Python types."""
    if isinstance(value, dict):
        return {key: make_json_safe(item) for key, item in value.items()}

    if isinstance(value, list):
        return [make_json_safe(item) for item in value]

    if isinstance(value, tuple):
        return [make_json_safe(item) for item in value]

    if isinstance(value, np.generic):
        return value.item()

    return value


def persist_training_outputs(
    version: str,
    winner: dict[str, Any],
    ranked_results: list[dict[str, Any]],
    error_analysis: dict[str, Any],
    feature_importance: list[dict[str, Any]],
    model_dir: str = DEFAULT_MODEL_DIR,
) -> tuple[Path, Path, Path]:
    """Persist the winning model, metadata, and markdown report."""
    output_dir = Path(model_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger(__name__)

    model_file = output_dir / f"model_{version}.pkl"
    joblib.dump(
        {
            "model": winner["model"],
            "preprocessor": winner["preprocessor"],
            "feature_names": FEATURE_NAMES,
            "model_type": winner["model_type"],
            "model_name": winner["name"],
        },
        model_file,
    )

    metadata_file = output_dir / f"metadata_{version}.json"
    metadata = {
        "version": version,
        "timestamp": datetime.now().isoformat(),
        "model_type": winner["model_type"],
        "selected_model": {
            "name": winner["name"],
            "type": winner["model_type"],
            "selection_priority": list(SELECTION_PRIORITY),
            "conclusion": build_conclusion(winner),
        },
        "metrics": winner["metrics"],
        "deployment_ready": winner["deployment_ready"],
        "failed_checks": winner["failed_checks"],
        "model_comparison": [
            {
                "name": result["name"],
                "model_type": result["model_type"],
                "selection_rank": result["selection_rank"],
                "deployment_ready": result["deployment_ready"],
                "failed_checks": result["failed_checks"],
                "metrics": result["metrics"],
                "selected": result["selected"],
            }
            for result in ranked_results
        ],
        "error_analysis": error_analysis,
        "feature_importance": feature_importance,
    }
    metadata_file.write_text(json.dumps(make_json_safe(metadata), indent=2), encoding="utf-8")

    report_file = output_dir / f"report_{version}.md"
    report_file.write_text(
        build_markdown_report(version, ranked_results, winner, error_analysis, feature_importance),
        encoding="utf-8",
    )

    logger.info("Saved model artifact: %s", model_file)
    logger.info("Saved metadata: %s", metadata_file)
    logger.info("Saved report: %s", report_file)
    return model_file, metadata_file, report_file


def compare_models(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    X_val: pd.DataFrame,
    y_val: pd.Series,
    criteria: dict[str, float],
) -> tuple[dict[str, Any], list[dict[str, Any]], dict[str, Any], list[dict[str, Any]]]:
    """Train all candidate models, compare them, and return the winner."""
    logger = logging.getLogger(__name__)
    results = []

    for candidate in build_candidate_models():
        logger.info("Training candidate: %s", candidate["name"])

        preprocessor = candidate["preprocessor"]
        X_train_processed = preprocessor.fit_transform(X_train)
        candidate["model"].fit(X_train_processed, y_train)

        evaluation = evaluate_model(candidate["model"], preprocessor, X_val, y_val)
        metrics = evaluation["metrics"]
        deployment_ready, failed_checks = check_deployment_criteria(metrics, criteria)

        logger.info(
            "%s | recall=%.4f precision=%.4f f1=%.4f roc_auc=%.4f ready=%s",
            candidate["name"],
            metrics["recall"],
            metrics["precision"],
            metrics["f1_score"],
            metrics["roc_auc"],
            deployment_ready,
        )

        results.append(
            {
                "name": candidate["name"],
                "model_type": candidate["model_type"],
                "model": candidate["model"],
                "preprocessor": preprocessor,
                "metrics": metrics,
                "deployment_ready": deployment_ready,
                "failed_checks": failed_checks,
                "y_pred": evaluation["y_pred"],
                "y_scores": evaluation["y_scores"],
            }
        )

    winner, ranked_results = select_best_candidate(results)
    error_analysis = analyze_prediction_errors(X_val, y_val, winner["y_pred"], winner["y_scores"])
    feature_importance = compute_feature_importance(winner["model"], winner["preprocessor"], X_val, y_val)
    return winner, ranked_results, error_analysis, feature_importance


def run_training(train_data: str, val_data: str, criteria_file: str, model_dir: str) -> None:
    """Run the full training workflow."""
    logger = logging.getLogger(__name__)
    logger.info("=" * 72)
    logger.info("STARTING TRAINING AND MODEL COMPARISON")
    logger.info("=" * 72)

    version = get_next_version(model_dir)
    logger.info("[1/4] Version: %s", version)

    logger.info("[2/4] Loading training and validation data")
    X_train, y_train, X_val, y_val = load_training_data(train_data, val_data)

    logger.info("[3/4] Training candidate models")
    with open(criteria_file, encoding="utf-8") as file_handle:
        criteria = yaml.safe_load(file_handle).get("deployment_criteria", {})

    winner, ranked_results, error_analysis, feature_importance = compare_models(
        X_train, y_train, X_val, y_val, criteria
    )

    logger.info("[4/4] Persisting artifacts and reports")
    persist_training_outputs(
        version=version,
        winner=winner,
        ranked_results=ranked_results,
        error_analysis=error_analysis,
        feature_importance=feature_importance,
        model_dir=model_dir,
    )

    logger.info("=" * 72)
    logger.info("TRAINING COMPLETED")
    logger.info("Selected model: %s", winner["name"])
    logger.info("Conclusion: %s", build_conclusion(winner))
    logger.info("=" * 72)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train and compare models for the Student Depression project",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--train-data", default=DEFAULT_TRAIN_DATA)
    parser.add_argument("--val-data", default=DEFAULT_VAL_DATA)
    parser.add_argument("--criteria-file", default=DEFAULT_CRITERIA_FILE)
    parser.add_argument("--model-dir", default=DEFAULT_MODEL_DIR)
    parser.add_argument("--log-file", default="logs/train.log")

    args = parser.parse_args()
    setup_logging(args.log_file)
    run_training(args.train_data, args.val_data, args.criteria_file, args.model_dir)


if __name__ == "__main__":
    main()
